#!/usr/bin/env php
<?php

/*
 * This file is part of the Laravel framework.
 *
 * (c) Taylor Otwell <taylor@laravel.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

exit($app->handleCommand(new ArgvInput()));
